export const PRODUCTS_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_LIST_SUCCESS ="PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL= "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS ="PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL= "PRODUCT_DETAIL_FAIL";

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_ITEM = "REMOVE_ITEM"

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESSFUL ="LOGIN_REQUEST_SUCCESSFUL";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL"

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_REQUEST_SUCCESSFUL ="REGISTER_REQUEST_SUCCESSFUL";
export const REGISTER_REQUEST_FAIL = "REGISTER_REQUEST_FAIL"

export const SAVE_SHIPPING = "SAVE_SHIPPING";

export const SAVE_PAYMENT = "SAVE_PAYMENT"

export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";
export const LOGIN_ADMIN_FAIL = "LOGIN_ADMIN_FAIL"

export const PRODUCTS_ADMIN = "PRODUCTS_ADMIN";

export const ALL_PRODUCTS = "PRODUCTS_ADMIN";
export const PRICE = "PRODUCTS_ADMIN";
export const CATEGORY = "PRODUCTS_ADMIN";
export const CATEGORYCOMBO = "PRODUCTS_ADMIN";
export const CLEAR = "PRODUCTS_ADMIN";







